AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppPrefix:
    Type: String
    Description: Application Prefix
    Default: amx-ppl-cc
  AppPrefixUpper:
    Type: String
    Description: Application Prefix
    Default: AMX-PPL-CC
  AWSEnvironment:
    Type: String
    Description: Sort of AWS AMX environment
    AllowedValues:
      - "PROD"
      - "DES"
      - "QA"
    Default: "DES"
  EmailNotification:
    Type: String
    Description: Email ID to send notifications
    Default: 'guillermo.gutierrez@rackspace.com'
  RepoConnectionArn:
    Type: String
    Default: 'arn:aws:codestar-connections:us-east-1:983406763236:connection/05ba9103-71fd-487e-9ad6-61b5c8201ef3'
    Description: ARN of github coneection and AWS
  GitHubRepositoryName:
    Type: String
    Default: 'guillermo-gutierrez/eks-automation-2'
    Description: >
      Name of the GitHub repository containing the CloudFormation template being deployed.
  GitHubIntegrationBranch:
    Type: String
    Default: main
    Description: >
      Git branch on which integration occurs. Typical value here would be "main" but might differ
      for your specific use case
  IamStackName:
    Type: String
    Default: "AMX-PPL-CC-DES-IAM-PERMISSIONS-EKS"
    Description: Escribe el nombre del stack que se utilizó para generar los roles de IAM
  EksCodebuildCMK:
    Type: String
    Description: Define the ARN of CMK key for CodeBuild
    Default: 'arn:aws:kms:us-east-1:983406763236:key/571266d4-f4d4-45ba-8ef0-998613789a8a'
  EksSecretsCMK:
    Type: String
    Description: Define the ARN of CMK key for CodeBuild
    Default: 'arn:aws:kms:us-east-1:983406763236:key/571266d4-f4d4-45ba-8ef0-998613789a8a'
  CodePipelineS3BucketName:
    Type: String
    Description: CodePipeline Artifact S3 Bucket Name
    Default: 'amx-ppl-cc-des-s3-create-eks-1'

# VPC Parameters
#  vpcId:
#    Type: AWS::EC2::VPC::Id
#    Description: Define VPC ID for CodeBuild
#    Default:
#  cidrBlock:
#    Type: String
#    Description: VPCs CIDR Block
#    Default:
#  sharedNodeSg:
#    Type: String
#    Description: Shared Node Security Group
#    Default:
#  subnet1:
#    Type: AWS::EC2::Subnet::Id
#    Description: Define the Subnets ID
#    Default:
#  subnet2:
#    Type: AWS::EC2::Subnet::Id
#    Description: Define the Subnets ID
#    Default:

# EKS Parameters

  eksClusterVersion:
    Type: String
    Description: Kubernetes version number
    Default: 1.24

# Policy Parameters

  CloudWatchWriteAccessPolicyArn:
    Type: String
    Description: Cloudwatch Write Access Policy ARN
    Default: arn:aws:iam::983406763236:policy/amx-ppl-cc-des-iam-p-cwtch-write
  S3ReadWriteAccessPolicyArn:
    Type: String
    Description: S3 Read Write Access Policy ARN
    Default: arn:aws:iam::983406763236:policy/amx-ppl-cc-des-iam-p-s3-read-write
  SMKMSReadAccessPolicyArn:
    Type: String
    Description: SM KMS Read Access Policy ARN
    Default: arn:aws:iam::983406763236:policy/amx-ppl-cc-des-iam-p-sm-kms-read
  EksIamRoleArn:
    Type: String
    Description: EKS IAM Role ARN
    Default: arn:aws:iam::983406763236:role/amx-ppl-cc-des-iam-rol-eks-deployer
  CbEksIamRoleArn:
    Type: String
    Description: CodeBuild EKS IAM Role ARN
    Default: arn:aws:iam::983406763236:role/AMX-PPL-CB-EKS-983406763236-us-east-1

Resources:
  EksSnsApprovalNotification:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${AppPrefixUpper}-${AWSEnvironment}-SNS-EKS-APPROVAL'
      FifoTopic: false
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS
      TopicName: !Sub '${AppPrefixUpper}-${AWSEnvironment}-SNS-EKS-APPROVAL'

  EksSnsApprovalSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailNotification
      Protocol: 'email'
      TopicArn: !Ref EksSnsApprovalNotification

  EksSnsPipelinesNotification:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${AppPrefixUpper}-${AWSEnvironment}-SNS-EKS-EVENTS'
      FifoTopic: false
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS
      TopicName: !Sub '${AppPrefixUpper}-${AWSEnvironment}-SNS-EKS-EVENTS'

  EksEventBridgeToToSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: !Ref EksSnsPipelinesNotification
      Topics: 
        - !Ref EksSnsPipelinesNotification 

  EksCodePipelineStateFailureEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AppPrefixUpper}-${AWSEnvironment}-CW-EKS-PIPELINE-RULE'
      Description: 'A CloudWatch Event Rule that sends a notification to provide notice over failed events from Infrastructure EKS pipeline'
      State: 'ENABLED'
      Targets:
        - Arn: !Ref EksSnsPipelinesNotification
          Id: !GetAtt EksSnsPipelinesNotification.TopicName
          InputTransformer:
            InputTemplate: '"The Pipeline has failed. Go to https://console.aws.amazon.com/codepipeline/home?region=us-east-1#/view/"'
            InputPathsMap:
              pipeline: "$.detail.pipeline"
      EventPattern:
        detail-type:
          - 'CodePipeline Pipeline Execution State Change'
        source:
          - 'aws.codepipeline'
        detail:
          event:
            - FAILED
      RoleArn:
          Fn::ImportValue: !Sub "${IamStackName}-EksAmazonCloudWatchEventRole"

  EksCodebuildStateFailureEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Sub '${AppPrefixUpper}-${AWSEnvironment}-CW-CODEBUILD-EKS-RULE'
      Description: "Rule for sending failure notifications to SNS topic"
      EventPattern:
        source:
          - aws.codebuild
        detail-type:
          - CodeBuild Build State Change
        detail:
          project-name:
            - CodeBuildProjects
          build-status:
            - FAILED
      State: "ENABLED"
      Targets:
        - Arn: !Ref EksSnsPipelinesNotification
          Id: !GetAtt EksSnsPipelinesNotification.TopicName
          InputTransformer:
            InputTemplate: '"The project <project-name> has the next status: <build-status>. You can check <deep-link>"'
            InputPathsMap:
              project-name: "$.detail.project-name"
              build-status: "$.detail.build-status"
              deep-link: "$.detail.additional-information.logs.deep-link"
      RoleArn:
          Fn::ImportValue: !Sub "${IamStackName}-EksAmazonCloudWatchEventRole"

  EksConfigureLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/paperless/${AppPrefixUpper}-${AWSEnvironment}-CW-LOGGROUP-EKS-CONFIGURE'
      RetentionInDays: 90
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS

  EksCodeBuildConfigureSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Codebuild
      VpcId:
        Fn::ImportValue: PPL-CC-VPCID
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS
          
  EksCodeBuildConfigureEgressSecurityGroup:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EksCodeBuildConfigureSecurityGroup
      CidrIp: '0.0.0.0/0'
      FromPort: -1
      ToPort: -1
      IpProtocol: '-1'

  EksCodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      EncryptionKey: !Ref EksCodebuildCMK
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/deploy-eks.yaml
      TimeoutInMinutes: 30
      QueuedTimeoutInMinutes: 30
      Environment:
          Type: LINUX_CONTAINER
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
          ImagePullCredentialsType: CODEBUILD
          ComputeType: BUILD_GENERAL1_SMALL
          PrivilegedMode: false
          EnvironmentVariables:
            - Name: AppPrefix
              Value: !Ref AppPrefix
            - Name: environment
              Value: !Ref AWSEnvironment
            - Name: keyARN
              Value: !Ref EksSecretsCMK
            - Name: vpcId
              Value:
                Fn::ImportValue: PPL-CC-VPCID
            - Name: cidrBlock
              Value:
                Fn::ImportValue: PPL-CC-VPCCidrBlock
            - Name: sharedNodeSg
              Value:
                Fn::ImportValue: PPL-CC-APPSecurityGroupID
            - Name: subnet1
              Value:
                Fn::ImportValue: PPL-CC-Subnet03ID
            - Name: subnet2
              Value:
                Fn::ImportValue: PPL-CC-Subnet04ID
            - Name: eksClusterVersion
              Value: !Ref eksClusterVersion
            - Name: CloudWatchWriteAccessPolicyArn
              Value: !Ref CloudWatchWriteAccessPolicyArn
            - Name: S3ReadWriteAccessPolicyArn
              Value: !Ref S3ReadWriteAccessPolicyArn
            - Name: SMKMSReadAccessPolicyArn
              Value: !Ref SMKMSReadAccessPolicyArn
            - Name: EksIamRoleArn
              Value: !Ref EksIamRoleArn
            - Name: CbEksIamRoleArn
              Value: !Ref CbEksIamRoleArn
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref EksConfigureLogGroup
          Status: ENABLED
      Name: !Sub '${AppPrefixUpper}-${AWSEnvironment}-CB-DEPLOY-EKS'
      ServiceRole: 
        Fn::ImportValue: !Sub "${IamStackName}-EksCodeBuildRole"
      VpcConfig:
          SecurityGroupIds: 
            - !GetAtt EksCodeBuildConfigureSecurityGroup.GroupId
          Subnets: 
            - Fn::ImportValue: PPL-CC-Subnet03ID
          VpcId:
            Fn::ImportValue: PPL-CC-VPCID
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS

  EksCodeBuildConfigureProject:
    Type: AWS::CodeBuild::Project
    Properties:
      EncryptionKey: !Ref EksCodebuildCMK
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec/configure-eks.yaml
      TimeoutInMinutes: 30
      QueuedTimeoutInMinutes: 30
      Environment:
          Type: LINUX_CONTAINER
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
          ImagePullCredentialsType: CODEBUILD
          ComputeType: BUILD_GENERAL1_SMALL
          PrivilegedMode: false
          EnvironmentVariables:
            - Name: AppPrefix
              Value: !Ref AppPrefix
            - Name: environment
              Value: !Ref AWSEnvironment
            - Name: keyARN
              Value: !Ref EksSecretsCMK
            - Name: vpcId
              Value:
                Fn::ImportValue: PPL-CC-VPCID
            - Name: cidrBlock
              Value:
                Fn::ImportValue: PPL-CC-VPCCidrBlock
            - Name: sharedNodeSg
              Value:
                Fn::ImportValue: PPL-CC-APPSecurityGroupID
            - Name: subnet1
              Value:
                Fn::ImportValue: PPL-CC-Subnet03ID
            - Name: subnet2
              Value:
                Fn::ImportValue: PPL-CC-Subnet04ID
            - Name: eksClusterVersion
              Value: !Ref eksClusterVersion
            - Name: CloudWatchWriteAccessPolicyArn
              Value: !Ref CloudWatchWriteAccessPolicyArn
            - Name: S3ReadWriteAccessPolicyArn
              Value: !Ref S3ReadWriteAccessPolicyArn
            - Name: SMKMSReadAccessPolicyArn
              Value: !Ref SMKMSReadAccessPolicyArn
            - Name: EksIamRoleArn
              Value: !Ref EksIamRoleArn
            - Name: CbEksIamRoleArn
              Value: !Ref CbEksIamRoleArn
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref EksConfigureLogGroup
          Status: ENABLED
      Name: !Sub '${AppPrefixUpper}-${AWSEnvironment}-CB-CONFIGURE-EKS'
      ServiceRole: 
        Fn::ImportValue: !Sub "${IamStackName}-EksCodeBuildRole"
      VpcConfig:
          SecurityGroupIds: 
            - !GetAtt EksCodeBuildConfigureSecurityGroup.GroupId
          Subnets: 
            - Fn::ImportValue: PPL-CC-Subnet03ID
          VpcId:
            Fn::ImportValue: PPL-CC-VPCID
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS

  EksPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineS3BucketName
      Name: !Sub '${AppPrefixUpper}-${AWSEnvironment}-PIPELINE-DEPLOY-EKS'
      RestartExecutionOnUpdate: false
      RoleArn:
        Fn::ImportValue: !Sub "${IamStackName}-EksPipelineRole"
      Stages:
        - Name: Checkout
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref RepoConnectionArn
                FullRepositoryId: !Ref GitHubRepositoryName
                BranchName: !Ref GitHubIntegrationBranch
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: ManualApprovalDeployEKS
          Actions:
            - Name: ManualApprovalDeployEKS
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
        - Name: DeployEKS
          Actions:
            - Name: DeployEKS
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref EksCodeBuildDeployProject
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: ManualApprovalConfigureEKS
          Actions:
            - Name: ManualApprovalConfigureEKS
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
        - Name: ConfigureEKS
          Actions:
            - Name: ConfigureEKS
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref EksCodeBuildConfigureProject
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
      Tags:
        - Key: Project
          Value: PaperlessCC
        - Key: Aplication-ID
          Value: ATOS-N1-202209-Dynamics
        - Key: Application-Role
          Value: Web
        - Key: CF-Version
          Value: "1"
        - Key: Owner
          Value: "Oswaldo Javier Contreras R"
        - Key: Cost-Center
          Value: "120101"
        - Key: Customer
          Value: External
        - Key: Confidentiality
          Value: Medium
        - Key: Compliance
          Value: PCI
        - Key: Environment
          Value: !Ref AWSEnvironment
        - Key: Account-ID
          Value: !Sub "${AWS::AccountId}"
        - Key: Area
          Value: ATOS
